### ISSUE TITLE
[에코노베이션] 디자인 패턴으로 알아보는 IDP 설계 스토리

### ISSUE THREAD

**Issue by BlackBean99** [D2CAMPUS-PARTNER/2022-SEMINAR#4]
#### 발표자 정보  
- 이서현 /  3학년  / ymecca730135@gmail.com

#### 발표 내용
- 에코노베이션 회원 관리 서버 기획부터 지금까지
- 모놀리틱 프로젝트를 MSA형태의 회원 관리 서버로 분리 과정
- 디자인 패턴 적용을 통해 인프라 확장. JWT를 관리하는 Redis 분리에 적용 과정

#### 대상 요약 
- 서버 아키텍처에 관심이 많으신 분
- 지속 가능한 서버 구축에 관심이 있으신 분

#### 발표 자료 
- 추후 등록 예정

#### 기타 
 - 발표시간 : 20min
 - Keyword 👍🏻  `MSA` , `Spring`, `Design Pattern` , `Hexagonal Architecture`, `JWT`, `Redis`, `OOP`

**Comment by Kang-heesuk** [comment]
다음 세미나로 이월합니다. :)
