### ISSUE TITLE
[SCG] Node.js 백엔드를 위한 ORM 선택 가이드

### ISSUE THREAD

**Issue by Gongmeda** [D2CAMPUS-PARTNER/2022-SEMINAR#6]
#### 발표자 정보 
 - 변영민, 4학년, gongmeda@gmail.com

#### 발표 내용 + 대상 요약 
 - SCG의 프로젝트에서 사용한 ORM에 관한 고찰
 - Node.js 환경의 대표적인 ORM 종류 비교

#### 발표 자료 
 - 업데이트 예정

#### 기타 
 - 20min
 - `Backend` `Node.js` `ORM` `OOP`

**Comment by Kang-heesuk** [comment]
개인사정으로 다음 기회를 기약합니다 ;)
