### ISSUE TITLE
[주제 접수처] 나는 오늘 이 이야기가 하고 싶어서

### ISSUE THREAD

**Issue by Kang-heesuk** [D2CAMPUS-PARTNER/2022-SEMINAR#8]
네트워킹 시간에 나누고 싶은 이야기가 있으면 아래 댓글로 짤막한 주제를 남겨주세요!

해당 주제로 이야기 하실 수 있도록 자리를 마련해드릴께요~

**Comment by jaychang99** [comment]
저는 다른 단체나 개발 동아리가 코드 레포지토리를 어떻게, 어디서 관리하는지 알고 싶습니다! 이 부분에 대해서 이야기 나눠보면 좋을 것 같습니다!
또 배포는 어떤 방식으로 하는지 인프라 적인 부분에 대해서도 궁금합니다!
